---

- name: Remove centos packaged docker
  yum:
    name: docker
    state: absent

- name: Install Docker
  yum:
    name: "{{ docker_pkg_name }}"
    state: "{{ docker_pkg_state }}"
    disable_gpg_check: no
