---

- import_tasks: repo.yml
  tags:
    - "docker_repo"

- import_tasks: install.yml
  tags:
    - "docker_install"

- import_tasks: config.yml
  tags:
    - "docker_config"

- import_tasks: service.yml
  tags:
    - "docker_service"
