---

- name: Install Official Docker Repo
  yum_repository:
    name: docker
    description: Docker Repository
    baseurl: "https://download.docker.com/linux/centos/7/$basearch/{{ docker_repo_branch }}"
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: true
    enabled: true
  when: docker_repo_enabled
